#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: R2100
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        #以下的命令是：删除配置项。
        # sed -i '/xxx/d' .config       ###表示删除配置项
        # sed -i 's/xxx/yyy/g' .config  ###表示替换XXX为YYY
        ################################################################################################
        #系统服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' .config       ### 路由器https访问
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' .config        ### 利用URL语法在命令行下工作的文件传输工具
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config        ### HTOP 类top进程查看工具
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' .config ### openssl_exe 自动生成证书服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config        ### 浏览器的web shell工具
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config        ### NANO 文本编辑小工具
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config      ### IPERF3 测速工具
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config      ### VLMCSD（KMS激活服务器）
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config       ### LRZSZ，linux系统中类FTP的软件。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config         ### MTR，网络分析工具。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config      ### NAPT66是北邮学生开发的在较旧内核的Linux上实现ipv6 nat的内核模块
        #网易云音乐
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config         #网易云解锁
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config      #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        #穿透服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config     ### 阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config        ### 内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config        ### 内网穿透FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config    ### 内网穿透ZEROTIER
        #去广告
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config      ### 广告过滤，adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config   ### 广告过滤，koolproxy
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config ### 广告过滤，adguardhome
        #USB相关、下载软件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' .config            ### smaba和WINS服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' .config          ### 升级samba3为smaba3.6
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config            ### FTP服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config           ### 在线文件管理服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDYBIN/d' .config        ### 集成caddy执行文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config    ### transmission服务~1.5M
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config ### transmission网页端~0.8M
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config                     ### aria2服务~3.5M
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config         ### aria网页端~0.7M
        #DNS加速服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config     ### smartdns，解析加速
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN/d' .config  ### smartdns执行文件，不集成会从网上下载
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config ### dnsforwarder
        #科学上网
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config  ### SS plus+ ,客户端
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KUMASOCKS/d' .config    ### kumasocks，soc5服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config        ### v2ray 执行文件，不集成会从网上下载
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config       ### trojan执行文件，不集成会从网上下载
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config     ### SS server,服务端
        #校园网相关
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config    ### 校园网相关 MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config   ### 校园网相关 SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config      ### 校园网相关 MINIEAP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config  ### 校园网相关 NJIT_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' .config   ### 校园网相关 GDUT_DRCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config       ### 校园网相关 DOGCOM
        #其他服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config ### SOFTETHERVPN_SERVER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config ### SOFTETHERVPN_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config    ### SOFTETHERVPN_CMD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config             ### tunsafe vpn
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config               ### Socket CAT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config              ### srelay，可以不集成
        #电视棒
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config      ### RTL_SDR
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config     ### DUMP1090

        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        #系统相关
        echo "CONFIG_FIRMWARE_INCLUDE_HTTPS=y" >> .config       #路由器https访问（必须）
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=y" >> .config        #利用URL语法在命令行下工作的文件传输工具（必须）
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> .config        #htop 是Linux系统中的一个互动的进程查看器，与Linux传统的top相比，htop更加人性化。top太老了,推荐集成。
        echo "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y" >> .config #openssl_exe 自动生成证书服务（按需集成）
        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=y" >> .config        #基于浏览器的web shell工具（按需集成）
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> .config        #nano是一个小型好用的文本编辑器，（按需求集成）。
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config      #iperf3是一个网络速度测试工具,支持IPv4与IPv6,支持TCP、UDP、SCTP传输协议，（按需求集成）。
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config      #KMS激活服务器，（按需求集成）
        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config       #lrzsz是一款在linux里可代替ftp上传和下载的程序，可以不集成
        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config         #MTR是一款非常好用的网络分析工具，使管理员能够诊断和隔离网络错误，按需集成。
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config      #napt66是北邮学生开发的在较旧内核的Linux上实现ipv6 nat的内核模块，按需集成。
        #网易云音乐
        echo "CONFIG_FIRMWARE_INCLUDE_WYY=y" >> .config         #网易云解锁
        echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=y" >> .config      #网易云解锁GO版本执行文件（2M多）注意固件超大小,不集成会自动下载
        #穿透服务
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config     #阿里DDNS
        echo "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config        #内网穿透frpc
        echo "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config        #内网穿透frps
        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config    #内网穿透zerotier  ~1.3M
        #去广告
        echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config      #广告过滤，adbyby plus+
        echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=y" >> .config   #广告过滤，koolproxy
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #广告过滤，adguardhome
        #USB相关、下载软件
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD=n" >> .config        #开启smaba和WINS服务
        echo "CONFIG_FIRMWARE_INCLUDE_SMBD36=n" >> .config      #升级samba3为smaba3.6
        echo "CONFIG_FIRMWARE_INCLUDE_FTPD=n" >> .config        #开启FTP服务器
        echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config       #caddy，在线文件管理服务
        echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config    #集成caddy执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=n" >> .config              #transmission服务 ~1.5MB
        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=n" >> .config  #transmission网页端 ~0.8MB
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=n" >> .config                      #aria服务 ~3.5MB
        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=n" >> .config          #aira网页端 ~0.7MB
        #DNS加速服务
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config     #SmartDns服务
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config  #SmartDns执行文件，可以不集成，会从网上下载下来执行，不影响正常使用。 
        echo "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #dns forwarder
        #科学上网
        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config  #SS plus+，客户端
        echo "CONFIG_FIRMWARE_INCLUDE_KUMASOCKS=y" >> .config    #kumasocks,sock5客户端
        echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config        #集成v2ray 执行文件(3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config       #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        echo "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config     #SS server，服务端		
        #校园网相关
        echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config    #校园网相关 MentoHUST ：华中科技大的朋友开发出来的一款第三方锐捷认证工具！
        echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config   #校园网相关 SCUTCLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config      #校园网相关 MiniEAP 相对于原来的 Mentohust 更容易适配各个学校，并受到 mentohust 原作者推荐。
        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config  #校园网相关 NJIT_CLIENT
        echo "CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM=n" >> .config   #校园网相关 GDUT_DRCOM
        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config       #校园网相关 DOGCOM
        #其他服务
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #softethervpn_server，不需要集成
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #softethervpn_client，不需要集成
        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config    #softethervpn_cmd，不需要集成
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config             #tunsafe vpn，不需要集成
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config               #Socket CAT的主要特点就是在两个数据流之间建立通道，且支持众多协议和链接方式。
        echo "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config              #srelay，可以不集成
        #USB电视棒服务
        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config             #支持RTL-SDR电视棒服务,需USB电视棒硬件支持，不需要集成
        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config            #dump1090是专门为RTL-SDR设备设计的S模式解码器。这个程序可以配合电视棒实时在google map上显示飞机位置和飞行方向

        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
